### ISSUE TITLE
catalog query ``Language='all'`` returns no objects in some cases

### ISSUE THREAD

**Issue by thet** [collective/collective.catalogcleanup#16]
I have a site with very basic and custom multilingual support, using an Language index. Querying for ``Language='all'`` returns no elements from the catalog.
Can the language query be avoided?

**Comment by mauritsvanrees** [comment]
I tried with master on Plone 5.2, Python 3. Installed `plone.app.multilingual`, created Dutch, English and German content.  Result of catalogcleanup:

```
Handling catalog portal_catalog.
Brains in portal_catalog: 16
Brains in portal_catalog using standard filter is different: 0
portal_catalog: removed 0 brains without UID.
portal_catalog: removed no brains in object check.
portal_catalog: 0 non unique uids found.
portal_catalog: 0 items need new unique uids.
portal_catalog: total problems: 1

Ignored non existing catalog uid_catalog.

Ignored non existing catalog reference_catalog.

Done with catalog cleanup.
Dry run selected: aborted any transaction changes.
```

So one problem, which is the one that you report:

```
Brains in portal_catalog: 16
Brains in portal_catalog using standard filter is different: 0
```

First I thought `unrestrictedSearchResults` would help, but that gives the same problem. But recent versions of `Products.ZCatalog` have a `getAllBrains` method. I have a branch that tries to use this method and falls back to `unrestrictedSearchResults`.
There might be versions where `getAllBrains` does not exist and where `unrestrictedSearchResults` does not return anything, but that seems a small range of versions.

**Comment by thet** [comment]
I think this can be closed.
