### ISSUE TITLE
Remove support for Plone 3?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.catalogcleanup#4]
I can easily add support for testing this in Plone 4.0 and Plone 4.1; but it would be difficult to setup a build for Plone 3; does it make sense to try to maintain compatibility?

**Comment by mauritsvanrees** [comment]
It's fine with me to drop Plone 3 support.

This *is* still a package that I might use in the future before migrating a site from Plone 3 to Plone 4/5. I think this currently works, so it would be nice to not actually break Plone 3 support, even if we don't test it. But incompatibilities will undoubtedly creep in. It's not really worth it to lose sleep over.

I can always create an untested branch for Plone 3 compatibility if this is needed.

So: we can drop it.
